begin;

create table if not exists public.football_events (
    event_id bigint primary key references public.events(id) on delete cascade,
    minute text,
    status_detail text,
    round_key text,
    round_label text,
    leg integer,
    home_score integer,
    away_score integer,
    penalties_home integer,
    penalties_away integer,
    aggregate_home_score integer,
    aggregate_away_score integer,
    winner_participant_id bigint references public.participants(id) on delete set null,
    timeline jsonb not null default '[]'::jsonb,
    metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.football_standings_rows (
    id bigint generated by default as identity primary key,
    competition_season_id bigint not null references public.competition_seasons(id) on delete cascade,
    competition_phase_id bigint not null references public.competition_phases(id) on delete cascade,
    phase_group_id bigint not null references public.phase_groups(id) on delete cascade,
    participant_id bigint not null references public.participants(id) on delete cascade,
    position integer not null,
    played integer not null default 0,
    wins integer not null default 0,
    draws integer not null default 0,
    losses integer not null default 0,
    points integer not null default 0,
    goals_for integer not null default 0,
    goals_against integer not null default 0,
    goal_difference integer not null default 0,
    form jsonb not null default '[]'::jsonb,
    metadata jsonb not null default '{}'::jsonb,
    updated_at timestamptz not null default timezone('utc', now()),
    unique (competition_phase_id, phase_group_id, participant_id)
);

create table if not exists public.football_predictions (
    prediction_id uuid primary key references public.predictions(id) on delete cascade,
    home_score integer not null,
    away_score integer not null,
    metadata jsonb not null default '{}'::jsonb
);

commit;
