begin;

create extension if not exists pgcrypto;

drop view if exists public.dev_pickem_award_picks cascade;
drop view if exists public.dev_pickem_players cascade;
drop view if exists public.dev_pickem_match_picks cascade;
drop view if exists public.dev_pickem_group_picks cascade;
drop view if exists public.dev_user_pickems cascade;
drop view if exists public.dev_pickems cascade;
drop view if exists public.dev_match_predictions cascade;
drop view if exists public.dev_standings cascade;
drop view if exists public.dev_football_matches cascade;
drop view if exists public.dev_phase_groups cascade;
drop view if exists public.dev_seasons cascade;

drop table if exists public.pickem_award_results cascade;
drop table if exists public.pickem_award_picks cascade;
drop table if exists public.pickem_players cascade;
drop table if exists public.pickem_match_picks cascade;
drop table if exists public.pickem_group_picks cascade;
drop table if exists public.user_pickems cascade;
drop table if exists public.pickem_competitors cascade;
drop table if exists public.pickems cascade;
drop table if exists public.match_predictions cascade;
drop table if exists public.standings cascade;
drop table if exists public.football_match_events cascade;
drop table if exists public.football_matches cascade;
drop table if exists public.group_competitors cascade;
drop table if exists public.groups cascade;
drop table if exists public.phases cascade;
drop table if exists public.competitors cascade;
drop table if exists public.seasons cascade;
drop table if exists public.competitions cascade;
drop table if exists public.provider_refs cascade;
drop table if exists public.sync_state cascade;
drop table if exists public.sports cascade;

drop table if exists public.pickem_group_order_picks cascade;
drop table if exists public.pickem_entries cascade;
drop table if exists public.pickem_contests cascade;
drop table if exists public.pickem_award_candidates cascade;
drop table if exists public.pickem_match_picks cascade;
drop table if exists public.football_squad_players cascade;
drop table if exists public.football_players cascade;
drop table if exists public.football_predictions cascade;
drop table if exists public.football_standings_rows cascade;
drop table if exists public.football_events cascade;
drop table if exists public.event_participants cascade;
drop table if exists public.events cascade;
drop table if exists public.competition_season_participants cascade;
drop table if exists public.participant_members cascade;
drop table if exists public.participants cascade;
drop table if exists public.phase_groups cascade;
drop table if exists public.competition_phases cascade;
drop table if exists public.competition_seasons cascade;
drop table if exists public.predictions cascade;
drop table if exists public.scoring_runs cascade;

create table public.sports (
    id bigint generated by default as identity primary key,
    slug text not null unique,
    name text not null,
    is_active boolean not null default true,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

create table public.competitions (
    id bigint generated by default as identity primary key,
    sport_id bigint not null references public.sports(id) on delete cascade,
    slug text not null,
    name text not null,
    short_name text,
    country_code text,
    kind text not null default 'competition',
    provider_name text not null,
    provider_id text not null,
    is_active boolean not null default true,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now()),
    unique (sport_id, slug),
    unique (provider_name, provider_id)
);

create table public.seasons (
    id bigint generated by default as identity primary key,
    competition_id bigint not null references public.competitions(id) on delete cascade,
    slug text not null,
    name text not null,
    start_date date not null,
    end_date date not null,
    is_current boolean not null default false,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now()),
    unique (competition_id, slug)
);

create unique index seasons_current_unique
    on public.seasons (competition_id)
    where is_current = true;

create table public.phases (
    id bigint generated by default as identity primary key,
    season_id bigint not null references public.seasons(id) on delete cascade,
    slug text not null,
    name text not null,
    phase_type text not null check (phase_type in ('league_table', 'group_stage', 'knockout_round', 'final_stage')),
    order_index integer not null default 0,
    is_standings_phase boolean not null default false,
    is_bracket_phase boolean not null default false,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now()),
    unique (season_id, slug)
);

create table public.groups (
    id bigint generated by default as identity primary key,
    phase_id bigint not null references public.phases(id) on delete cascade,
    slug text not null,
    name text not null,
    order_index integer not null default 0,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now()),
    unique (phase_id, slug)
);

create table public.competitors (
    id bigint generated by default as identity primary key,
    sport_id bigint not null references public.sports(id) on delete cascade,
    kind text not null check (kind in ('club', 'national_team', 'athlete', 'pair', 'driver', 'rider')),
    slug text not null,
    name text not null,
    short_name text,
    country_code text,
    badge_url text,
    provider_name text not null,
    provider_id text not null,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now()),
    unique (sport_id, slug),
    unique (provider_name, provider_id)
);

create table public.group_competitors (
    id bigint generated by default as identity primary key,
    group_id bigint not null references public.groups(id) on delete cascade,
    competitor_id bigint not null references public.competitors(id) on delete cascade,
    created_at timestamptz not null default timezone('utc', now()),
    unique (group_id, competitor_id)
);

create table public.football_matches (
    id bigint generated by default as identity primary key,
    sport_id bigint not null references public.sports(id) on delete cascade,
    competition_id bigint not null references public.competitions(id) on delete cascade,
    season_id bigint not null references public.seasons(id) on delete cascade,
    phase_id bigint references public.phases(id) on delete set null,
    group_id bigint references public.groups(id) on delete set null,
    provider_name text not null,
    provider_id text not null,
    kickoff_at timestamptz not null,
    status text not null check (status in ('scheduled', 'live', 'finished', 'cancelled', 'postponed')),
    round_key text,
    round_label text,
    minute text,
    home_competitor_id bigint references public.competitors(id) on delete set null,
    away_competitor_id bigint references public.competitors(id) on delete set null,
    home_placeholder_label text,
    away_placeholder_label text,
    home_score integer,
    away_score integer,
    home_score_ht integer,
    away_score_ht integer,
    extra_time boolean not null default false,
    penalties_home integer,
    penalties_away integer,
    aggregate_home_score integer,
    aggregate_away_score integer,
    winner_competitor_id bigint references public.competitors(id) on delete set null,
    last_synced_at timestamptz,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now()),
    unique (provider_name, provider_id)
);

create index football_matches_season_idx on public.football_matches (season_id);
create index football_matches_kickoff_idx on public.football_matches (kickoff_at);

create table public.football_match_events (
    id bigint generated by default as identity primary key,
    football_match_id bigint not null references public.football_matches(id) on delete cascade,
    event_order integer not null default 0,
    minute text,
    kind text not null,
    side text,
    player_name text,
    assist_name text,
    title text,
    detail text,
    score jsonb,
    is_cancelled boolean not null default false,
    raw jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default timezone('utc', now()),
    unique (football_match_id, event_order, kind, minute, player_name)
);

create table public.standings (
    id bigint generated by default as identity primary key,
    season_id bigint not null references public.seasons(id) on delete cascade,
    phase_id bigint not null references public.phases(id) on delete cascade,
    group_id bigint not null references public.groups(id) on delete cascade,
    competitor_id bigint not null references public.competitors(id) on delete cascade,
    position integer not null,
    played integer not null default 0,
    wins integer not null default 0,
    draws integer not null default 0,
    losses integer not null default 0,
    points integer not null default 0,
    goals_for integer not null default 0,
    goals_against integer not null default 0,
    goal_difference integer not null default 0,
    form jsonb not null default '[]'::jsonb,
    updated_at timestamptz not null default timezone('utc', now()),
    unique (group_id, competitor_id)
);

create table public.match_predictions (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references auth.users(id) on delete cascade,
    football_match_id bigint not null references public.football_matches(id) on delete cascade,
    home_score integer not null check (home_score >= 0),
    away_score integer not null check (away_score >= 0),
    status text not null default 'open' check (status in ('open', 'locked', 'scored', 'cancelled')),
    points integer,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now()),
    scored_at timestamptz,
    unique (user_id, football_match_id)
);

create table public.pickems (
    id bigint generated by default as identity primary key,
    season_id bigint not null references public.seasons(id) on delete cascade,
    slug text not null unique,
    name text not null,
    group_deadline timestamptz not null,
    awards_deadline timestamptz not null,
    scoring_config jsonb not null default '{}'::jsonb,
    is_active boolean not null default true,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now()),
    unique (season_id)
);

create table public.pickem_competitors (
    id bigint generated by default as identity primary key,
    pickem_id bigint not null references public.pickems(id) on delete cascade,
    competitor_id bigint not null references public.competitors(id) on delete cascade,
    created_at timestamptz not null default timezone('utc', now()),
    unique (pickem_id, competitor_id)
);

create table public.user_pickems (
    id uuid primary key default gen_random_uuid(),
    pickem_id bigint not null references public.pickems(id) on delete cascade,
    user_id uuid not null references auth.users(id) on delete cascade,
    total_points integer not null default 0,
    group_points integer not null default 0,
    knockout_points integer not null default 0,
    award_points integer not null default 0,
    perfect_groups integer not null default 0,
    exact_scores integer not null default 0,
    scored_at timestamptz,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now()),
    unique (pickem_id, user_id)
);

create table public.pickem_group_picks (
    id bigint generated by default as identity primary key,
    user_pickem_id uuid not null references public.user_pickems(id) on delete cascade,
    group_id bigint not null references public.groups(id) on delete cascade,
    competitor_id bigint not null references public.competitors(id) on delete cascade,
    predicted_position integer not null check (predicted_position > 0),
    points integer,
    is_exact boolean,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now()),
    unique (user_pickem_id, group_id, competitor_id),
    unique (user_pickem_id, group_id, predicted_position)
);

create table public.pickem_match_picks (
    id bigint generated by default as identity primary key,
    user_pickem_id uuid not null references public.user_pickems(id) on delete cascade,
    football_match_id bigint not null references public.football_matches(id) on delete cascade,
    winner_competitor_id bigint not null references public.competitors(id) on delete cascade,
    home_score integer check (home_score is null or home_score >= 0),
    away_score integer check (away_score is null or away_score >= 0),
    points integer,
    winner_points integer,
    exact_score_points integer,
    is_winner_hit boolean,
    is_exact_score boolean,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now()),
    unique (user_pickem_id, football_match_id)
);

create table public.pickem_players (
    id bigint generated by default as identity primary key,
    pickem_id bigint not null references public.pickems(id) on delete cascade,
    competitor_id bigint not null references public.competitors(id) on delete cascade,
    provider_name text not null,
    provider_id text not null,
    name text not null,
    position text not null check (position in ('GK', 'DF', 'MF', 'FW')),
    shirt_number integer,
    club_name text,
    is_active boolean not null default true,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now()),
    unique (pickem_id, provider_name, provider_id)
);

create table public.pickem_award_picks (
    id bigint generated by default as identity primary key,
    user_pickem_id uuid not null references public.user_pickems(id) on delete cascade,
    award_key text not null check (award_key in ('mvp', 'top_scorer', 'best_goalkeeper', 'champion')),
    pickem_player_id bigint references public.pickem_players(id) on delete cascade,
    competitor_id bigint references public.competitors(id) on delete cascade,
    points integer,
    is_hit boolean,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now()),
    check (
        (award_key = 'champion' and competitor_id is not null and pickem_player_id is null)
        or (award_key <> 'champion' and pickem_player_id is not null and competitor_id is null)
    ),
    unique (user_pickem_id, award_key)
);

create table public.pickem_award_results (
    id bigint generated by default as identity primary key,
    pickem_id bigint not null references public.pickems(id) on delete cascade,
    award_key text not null check (award_key in ('mvp', 'top_scorer', 'best_goalkeeper', 'champion')),
    pickem_player_id bigint references public.pickem_players(id) on delete cascade,
    competitor_id bigint references public.competitors(id) on delete cascade,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now()),
    check (
        (award_key = 'champion' and competitor_id is not null and pickem_player_id is null)
        or (award_key <> 'champion' and pickem_player_id is not null and competitor_id is null)
    ),
    unique (pickem_id, award_key)
);

create table public.provider_refs (
    id bigint generated by default as identity primary key,
    provider_name text not null,
    resource_type text not null,
    external_id text not null,
    internal_table text not null,
    internal_id bigint not null,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now()),
    unique (provider_name, resource_type, external_id)
);

create table public.sync_state (
    id bigint generated by default as identity primary key,
    provider_name text not null,
    scope_ref text not null,
    state_key text not null,
    state_value jsonb not null default '{}'::jsonb,
    last_success_at timestamptz,
    last_error_at timestamptz,
    last_error_message text,
    updated_at timestamptz not null default timezone('utc', now()),
    unique (provider_name, scope_ref, state_key)
);

create view public.dev_seasons as
select s.id, c.name as competition_name, s.name as season_name, s.slug, s.start_date, s.end_date, s.is_current
from public.seasons s
join public.competitions c on c.id = s.competition_id;

create view public.dev_phase_groups as
select g.id, c.name as competition_name, s.name as season_name, p.name as phase_name, g.name as group_name, g.order_index
from public.groups g
join public.phases p on p.id = g.phase_id
join public.seasons s on s.id = p.season_id
join public.competitions c on c.id = s.competition_id;

create view public.dev_football_matches as
select
    m.id,
    c.name as competition_name,
    s.name as season_name,
    p.name as phase_name,
    g.name as group_name,
    m.kickoff_at,
    m.status,
    coalesce(home.name, 'Por decidir') as home_name,
    coalesce(away.name, 'Por decidir') as away_name,
    m.home_score,
    m.away_score,
    coalesce(winner.name, null) as winner_name,
    m.round_label
from public.football_matches m
join public.competitions c on c.id = m.competition_id
join public.seasons s on s.id = m.season_id
left join public.phases p on p.id = m.phase_id
left join public.groups g on g.id = m.group_id
left join public.competitors home on home.id = m.home_competitor_id
left join public.competitors away on away.id = m.away_competitor_id
left join public.competitors winner on winner.id = m.winner_competitor_id;

create view public.dev_standings as
select c.name as competition_name, s.name as season_name, p.name as phase_name, g.name as group_name, comp.name as competitor_name, st.*
from public.standings st
join public.seasons s on s.id = st.season_id
join public.competitions c on c.id = s.competition_id
join public.phases p on p.id = st.phase_id
join public.groups g on g.id = st.group_id
join public.competitors comp on comp.id = st.competitor_id;

create view public.dev_match_predictions as
select mp.*, pr.email, pr.username, dm.competition_name, dm.home_name, dm.away_name
from public.match_predictions mp
left join public.profiles pr on pr.id = mp.user_id
join public.dev_football_matches dm on dm.id = mp.football_match_id;

create view public.dev_pickems as
select p.*, c.name as competition_name, s.name as season_name
from public.pickems p
join public.seasons s on s.id = p.season_id
join public.competitions c on c.id = s.competition_id;

create view public.dev_user_pickems as
select up.*, pr.email, pr.username, dp.name as pickem_name, dp.competition_name, dp.season_name
from public.user_pickems up
left join public.profiles pr on pr.id = up.user_id
join public.dev_pickems dp on dp.id = up.pickem_id;

create view public.dev_pickem_group_picks as
select pgp.*, pr.email, pr.username, p.name as pickem_name, g.name as group_name, comp.name as competitor_name
from public.pickem_group_picks pgp
join public.user_pickems up on up.id = pgp.user_pickem_id
left join public.profiles pr on pr.id = up.user_id
join public.pickems p on p.id = up.pickem_id
join public.groups g on g.id = pgp.group_id
join public.competitors comp on comp.id = pgp.competitor_id;

create view public.dev_pickem_match_picks as
select pmp.*, pr.email, pr.username, p.name as pickem_name, dm.home_name, dm.away_name
from public.pickem_match_picks pmp
join public.user_pickems up on up.id = pmp.user_pickem_id
left join public.profiles pr on pr.id = up.user_id
join public.pickems p on p.id = up.pickem_id
join public.dev_football_matches dm on dm.id = pmp.football_match_id;

create view public.dev_pickem_players as
select pp.*, p.name as pickem_name, comp.name as team_name
from public.pickem_players pp
join public.pickems p on p.id = pp.pickem_id
join public.competitors comp on comp.id = pp.competitor_id;

create view public.dev_pickem_award_picks as
select pap.*, pr.email, pr.username, p.name as pickem_name, pp.name as player_name, comp.name as champion_name
from public.pickem_award_picks pap
join public.user_pickems up on up.id = pap.user_pickem_id
left join public.profiles pr on pr.id = up.user_id
join public.pickems p on p.id = up.pickem_id
left join public.pickem_players pp on pp.id = pap.pickem_player_id
left join public.competitors comp on comp.id = pap.competitor_id;

alter table public.sports enable row level security;
alter table public.competitions enable row level security;
alter table public.seasons enable row level security;
alter table public.phases enable row level security;
alter table public.groups enable row level security;
alter table public.competitors enable row level security;
alter table public.group_competitors enable row level security;
alter table public.football_matches enable row level security;
alter table public.football_match_events enable row level security;
alter table public.standings enable row level security;
alter table public.match_predictions enable row level security;
alter table public.pickems enable row level security;
alter table public.pickem_competitors enable row level security;
alter table public.user_pickems enable row level security;
alter table public.pickem_group_picks enable row level security;
alter table public.pickem_match_picks enable row level security;
alter table public.pickem_players enable row level security;
alter table public.pickem_award_picks enable row level security;
alter table public.pickem_award_results enable row level security;
alter table public.provider_refs enable row level security;
alter table public.sync_state enable row level security;

grant select, insert, update, delete on all tables in schema public to service_role;
grant usage, select on all sequences in schema public to service_role;

insert into public.sports (slug, name, is_active)
values ('football', 'Football', true)
on conflict (slug) do update
set name = excluded.name,
    is_active = excluded.is_active,
    updated_at = timezone('utc', now());

commit;
