begin;

create extension if not exists pgcrypto;

create table if not exists public.sports (
    id bigint generated by default as identity primary key,
    slug text not null unique,
    name text not null,
    is_active boolean not null default true,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.competitions (
    id bigint generated by default as identity primary key,
    sport_id bigint not null references public.sports(id) on delete cascade,
    slug text not null,
    name text not null,
    short_name text,
    country_code text,
    competition_kind text not null check (
        competition_kind in (
            'league',
            'cup',
            'tour',
            'team_tournament',
            'motorsport_championship'
        )
    ),
    participant_scope text not null check (
        participant_scope in ('club', 'national_team', 'individual', 'mixed')
    ),
    gender text not null check (gender in ('men', 'women', 'mixed', 'open')),
    variant_key text not null default 'regular',
    provider_name text not null,
    provider_competition_id text not null,
    is_active boolean not null default true,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now()),
    unique (sport_id, slug),
    unique (provider_name, provider_competition_id)
);

create table if not exists public.competition_seasons (
    id bigint generated by default as identity primary key,
    competition_id bigint not null references public.competitions(id) on delete cascade,
    season_key text not null,
    season_label text not null,
    season_type text not null check (season_type in ('split_year', 'calendar_year')),
    format_kind text not null check (
        format_kind in (
            'league',
            'knockout',
            'groups_knockout',
            'league_phase_knockout',
            'tour_draw',
            'team_tie_competition',
            'motorsport_calendar',
            'series_playoffs',
            'knockout_playoffs'
        )
    ),
    start_at date not null,
    end_at date not null,
    is_current boolean not null default false,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now()),
    unique (competition_id, season_key)
);

create unique index if not exists competition_seasons_current_unique
    on public.competition_seasons (competition_id)
    where is_current = true;

create table if not exists public.competition_phases (
    id bigint generated by default as identity primary key,
    competition_season_id bigint not null references public.competition_seasons(id) on delete cascade,
    parent_phase_id bigint references public.competition_phases(id) on delete set null,
    key text not null,
    name text not null,
    phase_type text not null check (
        phase_type in (
            'league_table',
            'league_phase',
            'group_stage',
            'knockout_round',
            'draw_round',
            'tie_round',
            'series_round',
            'final_stage',
            'session_group'
        )
    ),
    order_index integer not null,
    is_standings_phase boolean not null default false,
    is_bracket_phase boolean not null default false,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now()),
    unique (competition_season_id, key)
);

create table if not exists public.phase_groups (
    id bigint generated by default as identity primary key,
    competition_phase_id bigint not null references public.competition_phases(id) on delete cascade,
    key text not null,
    name text not null,
    order_index integer not null,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now()),
    unique (competition_phase_id, key)
);

create table if not exists public.participants (
    id bigint generated by default as identity primary key,
    sport_id bigint not null references public.sports(id) on delete cascade,
    kind text not null check (kind in ('team', 'player', 'athlete', 'pair')),
    slug text not null,
    code text,
    name text not null,
    short_name text,
    country_code text,
    badge_url text,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now()),
    unique (sport_id, slug)
);

create table if not exists public.participant_members (
    id bigint generated by default as identity primary key,
    parent_participant_id bigint not null references public.participants(id) on delete cascade,
    member_participant_id bigint not null references public.participants(id) on delete cascade,
    role text not null default 'member',
    order_index integer not null default 0,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now()),
    unique (parent_participant_id, member_participant_id)
);

create table if not exists public.competition_season_participants (
    id bigint generated by default as identity primary key,
    competition_season_id bigint not null references public.competition_seasons(id) on delete cascade,
    participant_id bigint not null references public.participants(id) on delete cascade,
    role text not null default 'entrant',
    seed integer,
    display_name_override text,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now()),
    unique (competition_season_id, participant_id)
);

create table if not exists public.events (
    id bigint generated by default as identity primary key,
    sport_id bigint not null references public.sports(id) on delete cascade,
    competition_id bigint not null references public.competitions(id) on delete cascade,
    competition_season_id bigint not null references public.competition_seasons(id) on delete cascade,
    competition_phase_id bigint references public.competition_phases(id) on delete set null,
    phase_group_id bigint references public.phase_groups(id) on delete set null,
    parent_event_id bigint references public.events(id) on delete set null,
    event_type text not null check (
        event_type in (
            'match',
            'series',
            'game',
            'tie',
            'rubber',
            'session',
            'race',
            'sprint',
            'qualifying',
            'practice'
        )
    ),
    slug text,
    title text,
    provider_name text not null,
    provider_event_id text not null,
    start_at timestamptz not null,
    end_at timestamptz,
    status text not null check (
        status in ('scheduled', 'live', 'finished', 'cancelled', 'postponed')
    ),
    sort_order integer,
    is_placeholder boolean not null default false,
    metadata jsonb not null default '{}'::jsonb,
    last_synced_at timestamptz,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now()),
    unique (provider_name, provider_event_id)
);

create table if not exists public.event_participants (
    id bigint generated by default as identity primary key,
    event_id bigint not null references public.events(id) on delete cascade,
    participant_id bigint references public.participants(id) on delete set null,
    slot_key text not null,
    slot_order integer not null default 0,
    placeholder_label text,
    is_placeholder boolean not null default false,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now()),
    unique (event_id, slot_key, slot_order)
);

create table if not exists public.predictions (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references auth.users(id) on delete cascade,
    sport_id bigint not null references public.sports(id) on delete cascade,
    competition_id bigint not null references public.competitions(id) on delete cascade,
    competition_season_id bigint not null references public.competition_seasons(id) on delete cascade,
    event_id bigint not null references public.events(id) on delete cascade,
    prediction_type text not null,
    status text not null check (status in ('open', 'locked', 'scored', 'cancelled')),
    points integer,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now()),
    scored_at timestamptz,
    unique (user_id, event_id, prediction_type)
);

create table if not exists public.provider_refs (
    id bigint generated by default as identity primary key,
    provider_name text not null,
    resource_type text not null,
    external_id text not null,
    internal_table text not null,
    internal_id bigint not null,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now()),
    unique (provider_name, resource_type, external_id)
);

create table if not exists public.sync_state (
    id bigint generated by default as identity primary key,
    provider_name text not null,
    scope_ref text not null,
    state_key text not null,
    state_value jsonb not null default '{}'::jsonb,
    last_success_at timestamptz,
    last_error_at timestamptz,
    last_error_message text,
    updated_at timestamptz not null default timezone('utc', now()),
    unique (provider_name, scope_ref, state_key)
);

create table if not exists public.scoring_runs (
    id bigint generated by default as identity primary key,
    event_id bigint not null references public.events(id) on delete cascade,
    prediction_type text not null,
    status text not null default 'pending',
    processed_count integer not null default 0,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

commit;
